# Generated by Django 5.1.1 on 2024-10-24 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradasplus', '0003_evento_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='entradasplus.evento'),
        ),
    ]
