# Generated by Django 5.1.1 on 2024-10-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradasplus', '0008_alter_perfilusuario_avatar_grupo_mensajegrupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
