# Generated by Django 5.1.1 on 2024-10-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradasplus', '0010_perfilusuario_apellidos_perfilusuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='foto',
            field=models.ImageField(blank=True, default='imagenes/default.jpg', null=True, upload_to='grupos/'),
        ),
    ]
