# Generated by Django 5.1.1 on 2024-11-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradasplus', '0012_alter_grupo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/people.png', null=True, upload_to='avatars/'),
        ),
    ]
