# Generated by Django 5.1.1 on 2024-11-13 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradasplus', '0014_mensajecalendario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='entradasplus.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reseña',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='entradasplus.evento'),
        ),
    ]
