# Generated by Django 5.1.1 on 2024-11-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradasplus', '0016_entrada_puntos_necesarios_perfilusuario_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='puntos_usados',
            field=models.IntegerField(default=0),
        ),
    ]
